language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk10

env:
  global:
    - ECLOX_ROOT_FOLDER=eclox.root
    - ECLOX_DOXYGEN_ROOT_FOLDER=eclox.doxygen.root
  matrix:
    - ECLIPSE_TARGET_PLATFORM=Eclipse-4.7
    - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8
    - ECLIPSE_TARGET_PLATFORM=Eclipse-4.9

install: true

script:
  - cd $TRAVIS_BUILD_DIR/$ECLOX_ROOT_FOLDER && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
  - cd $TRAVIS_BUILD_DIR/$ECLOX_DOXYGEN_ROOT_FOLDER && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
