language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

env:
  global:
    - ECLOX_ROOT_FOLDER=eclox.root
    - ECLOX_DOXYGEN_ROOT_FOLDER=eclox.doxygen.root
  matrix:
    - ECLIPSE_TARGET_PLATFORM=Eclipse-4.7
    - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8

install: true

before_script: cd $TRAVIS_BUILD_DIR

script:
  - cd $ECLOX_ROOT_FOLDER && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
  - cd $ECLOX_DOXYGEN_ROOT_FOLDER && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
