language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

env:
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.7
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8

install: true

script:
  - cd eclox.root && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
  - cd eclox.doxygen.root && mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
